### ISSUE TITLE
unable to download various books that are visible from the web interface.

### ISSUE THREAD

**Issue by ksrikanth** [cancerian0684/dli-downloader#4]
Hi,
    I was hoping to download sanskrit books using this tool, but downloads are failing for most books with the status "Not_Found" regularly.  I presume it could be because the tool is not able to decode the information properly.  Could you take a look.

As an example, I am attempting to download the book with barcode 1990020083144 described at http://dli.serc.iisc.ernet.in/cgi-bin/DBscripts/allmetainfo.cgi?barcode=1990020083144

   The log file is pasted below for reference.
Fetching metadata for Barcode : 1990020083144
java.net.SocketTimeoutException: connect timed out
java.net.UnknownHostException: www.dli.ernet.in
java.net.UnknownHostException: www.new1.dli.ernet.in
java.net.SocketTimeoutException: connect timed out
java.net.UnknownHostException: www.new.dli.ernet.in
java.net.SocketTimeoutException: connect timed out
java.net.SocketTimeoutException: connect timed out
Server URL & Metadata not found for the BarCode : 1990020083144
org.shunya.dli.MetadataNotFound: Server URL & Metadata not found for the BarCode : 1990020083144
	at org.shunya.dli.BarCodeInterpreter.collect(BarCodeInterpreter.java:63)
	at org.shunya.dli.DLIDownloader.fetchMetaData(DLIDownloader.java:64)
	at org.shunya.dli.DLIDownloader.fetchMetadataWithRetry(DLIDownloader.java:174)
	at org.shunya.dli.DLIDownloader.download(DLIDownloader.java:133)
	at org.shunya.dli.DownloadPanel.downloadWithRetry(DownloadPanel.java:786)
	at org.shunya.dli.DownloadPanel.access$1100(DownloadPanel.java:37)
	at org.shunya.dli.DownloadPanel$8.run(DownloadPanel.java:866)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Download Failed for this barcode : 1990020083144 - Chatush Sloki or Kanta Stotra vyakhyana, Yamunacharya Alwandar for Chatush sloki, 812p, PHILOSOPHY. PSYCHOLOGY, sanskrit (1913)

I am using v6.0.9

Thanks
Srikanth

**Comment by cancerian0684** [comment]
I have tried to fix this issue today, please try the latest build from https://www.shunyafoundation.com/free-dli-downloader-v6.1.0-software/dp/C755E13VGS
